##### BEGIN external-mapped/Dockerfile/image-header #####
FROM confluentinc/cp-kafka-connect:6.0.0
##### END external-mapped/Dockerfile/image-header #####

##### BEGIN external/Dockerfile/conteco #####
COPY ./healthcheck.sh /etc/confluent/docker/healthcheck.sh
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-ibmmq:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-ibmmq-sink:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:0.10.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-servicenow:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-syslog:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:latest
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:latest
##### END external/Dockerfile/conteco #####

##### BEGIN external-mapped/Dockerfile/labels-footer #####
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="external" \
      io.vcweb.name="kafka_connect" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="confluentinc/cp-kafka-connect:6.0.0" \
      io.vcweb.build="external-mapped" \
      io.vcweb.label="external.kafka-coonect - ContEco" \
      io.vcweb.description="Confluent Kafka Connect image with ContEco external prerequisites installed." \
      io.vcweb.repository="/conteco/repo"
##### END external-mapped/Dockerfile/labels-footer #####
